version: '2'
services:
  apache:
    build: apache
    links:
     - order
     - shipping
     - invoicing
    ports:
     - "8080:80"
  order:
    build: ../microservice-atom/microservice-atom-order
  shipping:
    build: ../microservice-atom/microservice-atom-shipping
    links:
     - order
  invoicing:
    build: ../microservice-atom/microservice-atom-invoicing
    links:
     - order

